import { describe, it, expect, beforeEach, vi } from "vitest";
import { NextRequest } from "next/server";
import { POST } from "@/app/api/ai/respond/route";

// Hoisted state for mocks
const hoisted = vi.hoisted(() => ({
  secureFetchMock: vi.fn(),
}));

// Mock secure fetch for AI service calls
vi.mock("@/lib/ai/secure-fetch", () => ({
  secureFetch: hoisted.secureFetchMock,
}));

// Mock fetch for internal API calls
global.fetch = vi.fn();

describe("API: /api/ai/respond", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    
    // Default AI service response
    hoisted.secureFetchMock.mockResolvedValue({
      ok: true,
      json: async () => ({
        result: "This is a smart AI response generated by the Phase 4.0 data-driven agent.",
        metadata: {
          confidence: 0.9,
          processing_time: 1200,
          agent_version: "Phase 4.0",
        },
      }),
    });

    // Default intent resolution response
    (global.fetch as any).mockResolvedValue({
      ok: true,
      json: async () => ({
        intent: "event_details",
        confidence: 0.85,
        context: {
          "event-context": {
            artists: [{ name: "Tulus", genre: "Premier vocalist" }],
            sponsors: [{ name: "Test Sponsor", tier: "Gold" }],
          },
        },
        metadata: {
          agent_version: "Phase 4.0 - Intent Resolution",
          data_sources: ["event-context"],
        },
      }),
    });
  });

  it("validates request schema and returns 400 for invalid input", async () => {
    const req = new NextRequest("http://localhost:3000/api/ai/respond", {
      method: "POST",
      body: JSON.stringify({}), // Missing required query
    });

    const res = await POST(req);
    const data = await res.json();

    expect(res.status).toBe(400);
    expect(data.error).toBe("Invalid request parameters");
    expect(Array.isArray(data.issues)).toBe(true);
  });

  it("generates smart response with intent resolution and context", async () => {
    const req = new NextRequest("http://localhost:3000/api/ai/respond", {
      method: "POST",
      body: JSON.stringify({
        query: "Tell me about the artists performing at the event",
        language: "en",
        sessionId: "11111111-1111-4111-8111-111111111111",
        userId: "user123",
      }),
    });

    const res = await POST(req);
    const data = await res.json();

    expect(res.status).toBe(200);
    expect(data.response).toBeTruthy();
    expect(data.metadata.agent_architecture).toBe("Phase 4.0 - Data-Driven Agent with Intent Resolution");
    expect(data.metadata.intent).toBe("event_details");
    expect(data.metadata.data_sources_used).toContain("event-context");
    expect(typeof data.metadata.processing_time).toBe("number");

    // Verify intent resolution was called
    expect(global.fetch).toHaveBeenCalledWith(
      expect.stringContaining("/api/ai/intent/resolve"),
      expect.objectContaining({
        method: "POST",
        body: expect.stringContaining("artists"),
      })
    );

    // Verify AI service was called with intelligent context
    expect(hoisted.secureFetchMock).toHaveBeenCalledWith(
      "/api/event/chat", // Event-specific endpoint for event_details intent
      expect.objectContaining({
        method: "POST",
        body: expect.objectContaining({
          query: "Tell me about the artists performing at the event",
          intent: "event_details",
          context_data: expect.objectContaining({
            artists: expect.any(Array),
          }),
        }),
      })
    );
  });

  it("skips intent resolution when intent is provided and useIntentResolution is false", async () => {
    const req = new NextRequest("http://localhost:3000/api/ai/respond", {
      method: "POST",
      body: JSON.stringify({
        query: "What are the sponsorship options?",
        intent: "business_partnership",
        useIntentResolution: false,
      }),
    });

    const res = await POST(req);
    const data = await res.json();

    expect(res.status).toBe(200);
    expect(data.metadata.intent).toBe("business_partnership");
    
    // Should not have called intent resolution
    expect(global.fetch).not.toHaveBeenCalledWith(
      expect.stringContaining("/api/ai/intent/resolve"),
      expect.any(Object)
    );

    // Should use chat/generate endpoint for business queries
    expect(hoisted.secureFetchMock).toHaveBeenCalledWith(
      "/api/chat/generate",
      expect.any(Object)
    );
  });

  it("determines correct AI endpoint based on intent", async () => {
    // Test prospect analysis intent
    (global.fetch as any).mockResolvedValueOnce({
      ok: true,
      json: async () => ({
        intent: "prospect_analysis",
        confidence: 0.92,
        context: { "chat-context": { sentiment: "positive" } },
      }),
    });

    const req = new NextRequest("http://localhost:3000/api/ai/respond", {
      method: "POST",
      body: JSON.stringify({
        query: "I'm very interested in partnership opportunities",
        sessionId: "11111111-1111-4111-8111-111111111111",
      }),
    });

    const res = await POST(req);
    const data = await res.json();

    expect(res.status).toBe(200);
    expect(data.metadata.ai_endpoint).toBe("/api/chat/generate"); // Business queries use chat/generate
  });

  it("selects relevant context based on intent", async () => {
    (global.fetch as any).mockResolvedValueOnce({
      ok: true,
      json: async () => ({
        intent: "prospect_analysis",
        confidence: 0.88,
        context: {
          "chat-context": {
            logs: [{ role: "user", message: "I'm interested" }],
            prospect: { name: "John Doe", company: "Test Corp" },
            sentiment: "positive",
          },
          "analytics-context": {
            behavior: { engagement_level: "high" },
            performance: { success_rate: 0.85 },
          },
        },
      }),
    });

    const req = new NextRequest("http://localhost:3000/api/ai/respond", {
      method: "POST",
      body: JSON.stringify({
        query: "Analyze my conversation history",
        sessionId: "11111111-1111-4111-8111-111111111111",
      }),
    });

    const res = await POST(req);

    expect(res.status).toBe(200);
    
    // Verify only relevant context was passed to AI
    const aiCall = hoisted.secureFetchMock.mock.calls[0];
    const contextData = aiCall[1].body.context_data;
    
    expect(contextData).toHaveProperty("chat_logs");
    expect(contextData).toHaveProperty("prospect");
    expect(contextData).toHaveProperty("sentiment");
    expect(contextData).toHaveProperty("user_behavior");
    
    // Should not include irrelevant context
    expect(contextData).not.toHaveProperty("performance");
  });

  it("generates business recommendations based on intent and context", async () => {
    (global.fetch as any).mockResolvedValueOnce({
      ok: true,
      json: async () => ({
        intent: "prospect_analysis",
        confidence: 0.95,
        context: {
          "chat-context": {
            sentiment: "positive",
            logs: new Array(8).fill({ role: "user", message: "test" }), // 8 messages = high engagement
          },
        },
      }),
    });

    const req = new NextRequest("http://localhost:3000/api/ai/respond", {
      method: "POST",
      body: JSON.stringify({
        query: "I'm really excited about this partnership opportunity",
        sessionId: "11111111-1111-4111-8111-111111111111",
      }),
    });

    const res = await POST(req);
    const data = await res.json();

    expect(res.status).toBe(200);
    expect(Array.isArray(data.recommendations)).toBe(true);
    
    const recommendations = data.recommendations;
    expect(recommendations.some((r: any) => r.title.includes("High Conversion"))).toBe(true);
    expect(recommendations.some((r: any) => r.title.includes("Engaged Prospect"))).toBe(true);
  });

  it("optimizes response for business partnership intent", async () => {
    (global.fetch as any).mockResolvedValueOnce({
      ok: true,
      json: async () => ({
        intent: "business_partnership",
        confidence: 0.87,
        context: {
          "event-context": {
            availability: { gold: 3, silver: 5 },
          },
        },
      }),
    });

    const req = new NextRequest("http://localhost:3000/api/ai/respond", {
      method: "POST",
      body: JSON.stringify({
        query: "What sponsorship packages are available?",
      }),
    });

    const res = await POST(req);
    const data = await res.json();

    expect(res.status).toBe(200);
    expect(data.urgency).toBeTruthy();
    expect(data.urgency.message).toContain("Limited sponsorship slots");
    expect(data.urgency.deadline).toContain("Early bird pricing");
  });

  it("handles AI service failures with intelligent fallback", async () => {
    hoisted.secureFetchMock.mockResolvedValue({
      ok: false,
      status: 500,
    });

    const req = new NextRequest("http://localhost:3000/api/ai/respond", {
      method: "POST",
      body: JSON.stringify({
        query: "When is the event?",
        language: "en",
      }),
    });

    const res = await POST(req);
    const data = await res.json();

    expect(res.status).toBe(200); // Should return 200 with fallback
    expect(data.response).toContain("August 7-8, 2026"); // Intelligent fallback for date query
    expect(data.metadata.error).toBe(true);
    expect(data.metadata.agent_version).toBe("Phase 4.0 - Fallback Mode");
  });

  it("provides multilingual fallback responses", async () => {
    hoisted.secureFetchMock.mockResolvedValue({
      ok: false,
      status: 500,
    });

    // Test Indonesian fallback with date query
    const reqId = new NextRequest("http://localhost:3000/api/ai/respond", {
      method: "POST",
      body: JSON.stringify({
        query: "Kapan waktu acaranya?", // Include "waktu" keyword for date detection
        language: "id",
      }),
    });

    const resId = await POST(reqId);
    const dataId = await resId.json();

    expect(resId.status).toBe(200);
    expect(dataId.response).toContain("7-8 Agustus 2026");
    expect(dataId.response).toContain("Arena Berlin");

    // Test German fallback with date query
    const reqDe = new NextRequest("http://localhost:3000/api/ai/respond", {
      method: "POST",
      body: JSON.stringify({
        query: "Wann ist die Veranstaltung?", // "Wann" should trigger date response
        language: "de",
      }),
    });

    const resDe = await POST(reqDe);
    const dataDe = await resDe.json();

    expect(resDe.status).toBe(200);
    expect(dataDe.response).toContain("7.-8. August 2026");
    expect(dataDe.response).toContain("Arena Berlin");
  });

  it("creates comprehensive context summary", async () => {
    (global.fetch as any).mockResolvedValueOnce({
      ok: true,
      json: async () => ({
        intent: "general_inquiry",
        confidence: 0.7,
        context: {
          "chat-context": {
            logs: [{ role: "user", message: "test1" }, { role: "assistant", message: "test2" }],
            sentiment: "neutral",
            prospect: { name: "Test User" },
          },
          "event-context": {
            sponsors: [{ name: "Sponsor 1" }, { name: "Sponsor 2" }],
            tiers: [{ name: "Gold" }],
            pricing_context: { total_revenue: "€1M" },
          },
          "analytics-context": {
            behavior: { engagement: "medium" },
            personalization: { theme: "dark" },
            events: [{ type: "click" }, { type: "view" }],
          },
        },
      }),
    });

    const req = new NextRequest("http://localhost:3000/api/ai/respond", {
      method: "POST",
      body: JSON.stringify({
        query: "General question about everything",
        sessionId: "11111111-1111-4111-8111-111111111111",
        userId: "user123",
      }),
    });

    const res = await POST(req);
    const data = await res.json();

    expect(res.status).toBe(200);
    
    const summary = data.context_summary;
    expect(summary.chat_summary).toEqual({
      total_messages: 2,
      sentiment: "neutral",
      has_prospect: true,
    });
    expect(summary.event_summary).toEqual({
      sponsors_count: 2,
      tiers_available: 1,
      has_pricing_context: true,
    });
    expect(summary.analytics_summary).toEqual({
      has_behavior_data: true,
      has_personalization: true,
      events_count: 2,
    });
  });

  it("includes proper response headers", async () => {
    const req = new NextRequest("http://localhost:3000/api/ai/respond", {
      method: "POST",
      body: JSON.stringify({
        query: "Test query",
      }),
    });

    const res = await POST(req);

    expect(res.status).toBe(200);
    expect(res.headers.get("Cache-Control")).toBe("no-cache, no-store, must-revalidate");
    expect(res.headers.get("X-AI-Intent")).toBe("event_details");
    expect(res.headers.get("X-AI-Version")).toBe("Phase-4.0");
  });
});